/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import javax.swing.JButton;

/**
 *
 * @author Jon
 */
public class VentanaAhorcado extends javax.swing.JFrame {

    
     String palabraOculta = "ABECEDARIUS";
     int numeroDeFallos= 0;
     
    /**
     * Creates new form VentanaAhorcado
     */
    public VentanaAhorcado() {
        initComponents();
        //inicializo el display del juego para que tenga
        //tantos guiones bajos y espacios como la palabra oculta
        String aux = "";
        for(int i=0; i<palabraOculta.length();i++){
            aux +="_ ";
        }
        display.setText(aux);
    }

    private void chequeaBoton(JButton boton){
            boton.setEnabled(false);
            chequeaLetra(boton.getText());
        
        
        
    }
    private void chequeaLetra(String letra){
        //leo lo que hay en pantalla y lo guardo en un String
        String palabraConGuiones = display.getText();
        
        //comparo la letra que ha sido pulsada con las letras de la palabra oculta
        char letraPulsada = letra.charAt(0);
        for(int i=0; i< palabraOculta.length(); i++){
            if(palabraOculta.charAt(i)==letra.charAt(0)){
                palabraConGuiones =
                        palabraConGuiones.substring(0, 2*i)/*trozo de la izquierda*/
                        + letra 
                        + palabraConGuiones.substring(2*i+1)/*trozo de la derecha*/;
                
            }
        }
        //actualizo el display para que muestre la letra acertada
        display.setText(palabraConGuiones);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonLetra16 = new javax.swing.JLabel();
        botonLetra17 = new javax.swing.JLabel();
        botonLetra18 = new javax.swing.JLabel();
        botonLetra19 = new javax.swing.JLabel();
        botonLetra20 = new javax.swing.JLabel();
        botonLetra21 = new javax.swing.JLabel();
        botonLetra22 = new javax.swing.JLabel();
        botonLetra23 = new javax.swing.JLabel();
        display = new javax.swing.JLabel();
        VisorImagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();

        botonLetra16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonLetra16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonLetra16.setText("A");
        botonLetra16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonLetra16MousePressed(evt);
            }
        });

        botonLetra17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonLetra17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonLetra17.setText("A");
        botonLetra17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonLetra17MousePressed(evt);
            }
        });

        botonLetra18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonLetra18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonLetra18.setText("A");
        botonLetra18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonLetra18MousePressed(evt);
            }
        });

        botonLetra19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonLetra19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonLetra19.setText("A");
        botonLetra19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonLetra19MousePressed(evt);
            }
        });

        botonLetra20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonLetra20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonLetra20.setText("A");
        botonLetra20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonLetra20MousePressed(evt);
            }
        });

        botonLetra21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonLetra21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonLetra21.setText("A");
        botonLetra21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonLetra21MousePressed(evt);
            }
        });

        botonLetra22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonLetra22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonLetra22.setText("A");
        botonLetra22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonLetra22MousePressed(evt);
            }
        });

        botonLetra23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonLetra23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonLetra23.setText("A");
        botonLetra23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonLetra23MousePressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        display.setText("_ _ _ _ _");

        VisorImagen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        VisorImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ahorcado_fin.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(51, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("A");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(51, 0, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 0, 51));
        jButton8.setText("B");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton8MousePressed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(51, 0, 0));
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 0, 51));
        jButton16.setText("C");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton16MousePressed(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(51, 0, 0));
        jButton24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton24.setForeground(new java.awt.Color(255, 0, 51));
        jButton24.setText("D");
        jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton24MousePressed(evt);
            }
        });

        jButton32.setBackground(new java.awt.Color(51, 0, 0));
        jButton32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 0, 51));
        jButton32.setText("E");
        jButton32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton32MousePressed(evt);
            }
        });

        jButton33.setBackground(new java.awt.Color(51, 0, 0));
        jButton33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton33.setForeground(new java.awt.Color(255, 0, 51));
        jButton33.setText("F");
        jButton33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton33MousePressed(evt);
            }
        });

        jButton34.setBackground(new java.awt.Color(51, 0, 0));
        jButton34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 0, 51));
        jButton34.setText("G");
        jButton34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton34MousePressed(evt);
            }
        });

        jButton35.setBackground(new java.awt.Color(51, 0, 0));
        jButton35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton35.setForeground(new java.awt.Color(255, 0, 51));
        jButton35.setText("I");
        jButton35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton35MousePressed(evt);
            }
        });

        jButton36.setBackground(new java.awt.Color(51, 0, 0));
        jButton36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton36.setForeground(new java.awt.Color(255, 0, 51));
        jButton36.setText("J");
        jButton36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton36MousePressed(evt);
            }
        });

        jButton37.setBackground(new java.awt.Color(51, 0, 0));
        jButton37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton37.setForeground(new java.awt.Color(255, 0, 51));
        jButton37.setText("H");
        jButton37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton37MousePressed(evt);
            }
        });

        jButton38.setBackground(new java.awt.Color(51, 0, 0));
        jButton38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton38.setForeground(new java.awt.Color(255, 0, 51));
        jButton38.setText("K");
        jButton38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton38MousePressed(evt);
            }
        });

        jButton39.setBackground(new java.awt.Color(51, 0, 0));
        jButton39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton39.setForeground(new java.awt.Color(255, 0, 51));
        jButton39.setText("L");
        jButton39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton39MousePressed(evt);
            }
        });

        jButton40.setBackground(new java.awt.Color(51, 0, 0));
        jButton40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton40.setForeground(new java.awt.Color(255, 0, 51));
        jButton40.setText("M");
        jButton40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton40MousePressed(evt);
            }
        });

        jButton41.setBackground(new java.awt.Color(51, 0, 0));
        jButton41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton41.setForeground(new java.awt.Color(255, 0, 51));
        jButton41.setText("N");
        jButton41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton41MousePressed(evt);
            }
        });

        jButton42.setBackground(new java.awt.Color(51, 0, 0));
        jButton42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton42.setForeground(new java.awt.Color(255, 0, 51));
        jButton42.setText("O");
        jButton42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton42MousePressed(evt);
            }
        });

        jButton43.setBackground(new java.awt.Color(51, 0, 0));
        jButton43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton43.setForeground(new java.awt.Color(255, 0, 51));
        jButton43.setText("P");
        jButton43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton43MousePressed(evt);
            }
        });

        jButton44.setBackground(new java.awt.Color(51, 0, 0));
        jButton44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton44.setForeground(new java.awt.Color(255, 0, 51));
        jButton44.setText("Ñ");
        jButton44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton44MousePressed(evt);
            }
        });

        jButton45.setBackground(new java.awt.Color(51, 0, 0));
        jButton45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton45.setForeground(new java.awt.Color(255, 0, 51));
        jButton45.setText("Q");
        jButton45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton45MousePressed(evt);
            }
        });

        jButton46.setBackground(new java.awt.Color(51, 0, 0));
        jButton46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton46.setForeground(new java.awt.Color(255, 0, 51));
        jButton46.setText("R");
        jButton46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton46MousePressed(evt);
            }
        });

        jButton47.setBackground(new java.awt.Color(51, 0, 0));
        jButton47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton47.setForeground(new java.awt.Color(255, 0, 51));
        jButton47.setText("S");
        jButton47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton47MousePressed(evt);
            }
        });

        jButton48.setBackground(new java.awt.Color(51, 0, 0));
        jButton48.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton48.setForeground(new java.awt.Color(255, 0, 51));
        jButton48.setText("T");
        jButton48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton48MousePressed(evt);
            }
        });

        jButton49.setBackground(new java.awt.Color(51, 0, 0));
        jButton49.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton49.setForeground(new java.awt.Color(255, 0, 51));
        jButton49.setText("V");
        jButton49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton49MousePressed(evt);
            }
        });

        jButton50.setBackground(new java.awt.Color(51, 0, 0));
        jButton50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton50.setForeground(new java.awt.Color(255, 0, 51));
        jButton50.setText("W");
        jButton50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton50MousePressed(evt);
            }
        });

        jButton51.setBackground(new java.awt.Color(51, 0, 0));
        jButton51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton51.setForeground(new java.awt.Color(255, 0, 51));
        jButton51.setText("U");
        jButton51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton51MousePressed(evt);
            }
        });

        jButton52.setBackground(new java.awt.Color(51, 0, 0));
        jButton52.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton52.setForeground(new java.awt.Color(255, 0, 51));
        jButton52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton52MousePressed(evt);
            }
        });

        jButton53.setBackground(new java.awt.Color(51, 0, 0));
        jButton53.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton53.setForeground(new java.awt.Color(255, 0, 51));
        jButton53.setText("X");
        jButton53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton53MousePressed(evt);
            }
        });

        jButton54.setBackground(new java.awt.Color(51, 0, 0));
        jButton54.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton54.setForeground(new java.awt.Color(255, 0, 51));
        jButton54.setText("Y");
        jButton54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton54MousePressed(evt);
            }
        });

        jButton55.setBackground(new java.awt.Color(51, 0, 0));
        jButton55.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton55.setForeground(new java.awt.Color(255, 0, 51));
        jButton55.setText("Z");
        jButton55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton55MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(VisorImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 104, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VisorImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLetra16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLetra16MousePressed
      chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_botonLetra16MousePressed

    private void botonLetra17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLetra17MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_botonLetra17MousePressed

    private void botonLetra18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLetra18MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_botonLetra18MousePressed

    private void botonLetra19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLetra19MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_botonLetra19MousePressed

    private void botonLetra20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLetra20MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_botonLetra20MousePressed

    private void botonLetra21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLetra21MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_botonLetra21MousePressed

    private void botonLetra22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLetra22MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_botonLetra22MousePressed

    private void botonLetra23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLetra23MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_botonLetra23MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton8MousePressed

    private void jButton16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton16MousePressed

    private void jButton24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton24MousePressed

    private void jButton32MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton32MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton32MousePressed

    private void jButton33MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton33MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton33MousePressed

    private void jButton34MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton34MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton34MousePressed

    private void jButton35MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton35MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton35MousePressed

    private void jButton36MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton36MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton36MousePressed

    private void jButton37MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton37MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton37MousePressed

    private void jButton38MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton38MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton38MousePressed

    private void jButton39MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton39MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton39MousePressed

    private void jButton40MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton40MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton40MousePressed

    private void jButton41MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton41MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton41MousePressed

    private void jButton42MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton42MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton42MousePressed

    private void jButton43MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton43MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton43MousePressed

    private void jButton44MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton44MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton44MousePressed

    private void jButton45MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton45MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton45MousePressed

    private void jButton46MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton46MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton46MousePressed

    private void jButton47MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton47MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton47MousePressed

    private void jButton48MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton48MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton48MousePressed

    private void jButton49MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton49MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton49MousePressed

    private void jButton50MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton50MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton50MousePressed

    private void jButton51MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton51MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton51MousePressed

    private void jButton52MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton52MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton52MousePressed

    private void jButton53MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton53MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton53MousePressed

    private void jButton54MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton54MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton54MousePressed

    private void jButton55MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton55MousePressed
        chequeaBoton ( (JButton) evt.getSource() );
    }//GEN-LAST:event_jButton55MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VisorImagen;
    private javax.swing.JLabel botonLetra16;
    private javax.swing.JLabel botonLetra17;
    private javax.swing.JLabel botonLetra18;
    private javax.swing.JLabel botonLetra19;
    private javax.swing.JLabel botonLetra20;
    private javax.swing.JLabel botonLetra21;
    private javax.swing.JLabel botonLetra22;
    private javax.swing.JLabel botonLetra23;
    private javax.swing.JLabel display;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton8;
    // End of variables declaration//GEN-END:variables
}
